version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gocritic
    - revive

  settings:
    revive:
      rules:
        - name: exported
          severity: warning

issues:
  exclude-dirs:
    - vendor
    - examples/.*/services
